<a href="https://colab.research.google.com/github/yesforshankar/datavisualizationandML/blob/master/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Create ordered sequence starting 0 using arange function
#creates 1-axis array. Use reshape to create n-d array

import numpy as np
x=150
y=int(x/10)
b = np.arange(x).reshape(y,10)
b=b+1
b


In [68]:
#string array
import numpy as np
a = np.array(['a','b']).reshape(1,2)
a

array([['a', 'b']], dtype='<U1')

In [0]:
#create sequences using python
#creates 1-axis array. Use reshape to create n-d array
import numpy as np
a=np.arange(1, 101, 1).reshape(20, 5)
a



In [69]:
#create floating point sequences using python
#creates 1-axis array.
#Byy default arrays include starting number, excludes ending number
import numpy as np
a=np.arange(1, 2, 0.1)
a

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [63]:
#print array of all 1s
#prints float by default 
import numpy as np
b=np.ones((3,4))
b


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [64]:
#print array of all 0s
#prints float by default. Use dtype to convert into int
import numpy as np
a= np.zeros((3,4), dtype="int16")
a 

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)